-- Flyway V1: Initial schema for Beer, BeerOrder, BeerOrderLine
-- Compatible with H2 and common SQL dialects

-- BEER table
CREATE TABLE IF NOT EXISTS beer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    beer_name VARCHAR(100) NOT NULL,
    beer_style VARCHAR(40) NOT NULL,
    upc VARCHAR(30) NOT NULL,
    quantity_on_hand INT,
    price NUMERIC(19, 2) NOT NULL,
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_beer_upc ON beer (upc);

-- BEER_ORDER table
CREATE TABLE IF NOT EXISTS beer_order (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    customer_ref VARCHAR(64),
    payment_amount NUMERIC(19, 2),
    status VARCHAR(40) NOT NULL,
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- BEER_ORDER_LINE table
CREATE TABLE IF NOT EXISTS beer_order_line (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    beer_order_id INT NOT NULL,
    beer_id INT NOT NULL,
    order_quantity INT NOT NULL,
    quantity_allocated INT NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL,
    created_date TIMESTAMP,
    updated_date TIMESTAMP,
    CONSTRAINT fk_bol_order FOREIGN KEY (beer_order_id) REFERENCES beer_order (id) ON DELETE CASCADE,
    CONSTRAINT fk_bol_beer FOREIGN KEY (beer_id) REFERENCES beer (id)
);

CREATE INDEX IF NOT EXISTS ix_bol_order ON beer_order_line (beer_order_id);
CREATE INDEX IF NOT EXISTS ix_bol_beer ON beer_order_line (beer_id);
