-- Flyway V2: Create customer table
-- Compatible with H2 and common SQL dialects

CREATE TABLE IF NOT EXISTS customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(40),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_customer_email ON customer(email);
