-- Flyway V2: Add beer_order_shipment table
-- H2-compatible DDL

CREATE TABLE IF NOT EXISTS beer_order_shipment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INT,
    beer_order_id INT NOT NULL,
    shipment_date DATE NOT NULL,
    carrier VARCHAR(100),
    tracking_number VARCHAR(120),
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

-- Add foreign key constraint in separate statement (guideline compliant)
ALTER TABLE beer_order_shipment
    ADD CONSTRAINT fk_bos_order FOREIGN KEY (beer_order_id) REFERENCES beer_order (id) ON DELETE CASCADE;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS ix_bos_order ON beer_order_shipment (beer_order_id);
CREATE INDEX IF NOT EXISTS ix_bos_shipdate ON beer_order_shipment (shipment_date);
